export const CREATE_DOG = 'CREATE_DOG';
export const GET_DOGS = 'GET_DOGS';
export const GET_TEMPERAMENTS= 'GET_TEMPERAMENTS';
export const FILTERED_TEMPERAMENT= 'FILTERED_TEMPERAMENT';
export const FILTERED_SOURCE= 'FILTERED_SOURCE';